
language: bash
warnings_are_errors: true
sudo: required

script: 
   - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
   - chmod 755 ./travis-tool.sh
   - echo "Execute the R testing scripts ..."
   - cd INTRO; Rscript intro.R; cd ..

env:
  global: 
    - CRAN: http://cran.rstudio.com

# the R packages used in the testing scripts should be added here 
r_packages: swirl, lintr, foreign

notifications:
  email:
    on_success: change
    on_failure: change

