language: r
warnings_are_errors: true
sudo: required

script:
    - R -e 'for (fn in list.files(".", recursive=TRUE, pattern=".Rmd")) {knitr::purl(fn, output = paste0(fn,".R"), documentation = 2); setwd(dirname(fn)); getwd(); source(paste0(basename(fn),".R")); unlink(paste0(basename(fn),".R")); setwd("../")}'
 
env:
  global: 
    - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

