
language: c
warnings_are_errors: true
sudo: required

script: 
   - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
   - chmod 755 ./travis-tool.sh
   - ./travis-tool.sh bootstrap
   - ./travis-tool.sh install_r lintr foreign
   - Rscript -e 'library(lintr); library(foreign)'
   - echo "Execute the R testing scripts ..."
   - cd INTRO; Rscript intro.R; cd ..

env:
  global: 
    - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

