
language: bash
warnings_are_errors: true
sudo: required

script: 
   - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
   - chmod 755 ./travis-tool.sh
   - ./travis-tool.sh install_aptget r-cran-foreign
   - cd INTRO; Rscript intro.R; cd ..

env:
  global: 
    - CRAN: http://cran.rstudio.com

r_packages: swirl, lintr, foreign

notifications:
  email:
    on_success: change
    on_failure: change

