
language: bash
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

script: 
   - Rscript -e 'install.packages("lintr")'
   - Rscript -e 'install.packages("foreign")'
   - cd INTRO; Rscript intro.R; cd ..

env:
  global: 
    - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

