
language: bash
warnings_are_errors: true
sudo: required

script: 
   - cd INTRO; Rscript intro.R; cd ..

env:
  global: 
    - CRAN: http://cran.rstudio.com

r_packages: swirl, lintr, foreign

notifications:
  email:
    on_success: change
    on_failure: change

