
language: bash
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

script: 
   - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
   - chmod 755 ./travis-tool.sh
   - ./travis-tool.sh install_aptget r-cran-foreign
   - Rscript -e 'install.packages("lintr")'
   - Rscript -e 'install.packages("foreign")'
   - cd INTRO; Rscript intro.R; cd ..

env:
  global: 
    - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

